### ISSUE TITLE
clarification about the `length` parameter

### ISSUE THREAD

**Issue by Demfier** [DongyaoZhu/VQ-VAE-WaveNet#6]
Hi @DongyaoZhu,

Thanks for the implementation. I am trying to understand the `-length` parameter. Based on the [generator code](https://github.com/DongyaoZhu/VQ-VAE-WaveNet/blob/master/dataset.py#L33), I get the sense that it's only taking a subset of samples available from a given sequence and is discarding the rest of it. For instance, if I have a 10-second clip with an sr=16k, I'll have about 160K samples in total, but using `length=12000` will only use a random slice of 12k samples from the whole sequence. Is my understanding correct? I was expecting something like a moving window so as to cover the whole sequence. Correct me if I am wrong.

**Comment by DongyaoZhu** [comment]
Hi Demfier,

Your understanding is correct that the length specifies the number of continuous samples of each audio example in a batch, although there's no moving window to cover the whole sequence since its just randomly selecting a start and cut for [start: start + length].

**Comment by Demfier** [comment]
Hi @DongyaoZhu,

Thanks. Then won't we be losing a lot of samples that the model could've potentially been trained on? For instance, if I have 30 audio clips, each around 50s long (sr=16k, let's say), then there's no guarantee that the model would've been exposed to the entirety of the dataset. Or are we relying on the `-step` hyperparameter and hoping if we have a sufficiently large value, it will cover *all* of 240e+6 (=30*50*16000) samples during training?

Also, what's the purpose of using `while=True` [here](https://github.com/DongyaoZhu/VQ-VAE-WaveNet/blob/master/dataset.py#L37) and at similar places? I think it will only be executed once regardless we have that line or not, no?

**Comment by DongyaoZhu** [comment]
Yes it's relying on having a large amount of steps to make sure the training examples seen in training as a whole is representative of the training corpus, but not necessarily be the corpus.

Note that the loop is giving training examples with `yield` and that the "gen" function is being returned itself. You could also take a look at examples [here](https://github.com/DongyaoZhu/Real-Time-Accent-Conversion/tree/master/datasets) for how to write dataset code.

**Comment by Demfier** [comment]
Thanks! That answers my questions.
